### ISSUE TITLE
Add CLI support

### ISSUE THREAD

**Issue by cgore** [outpace/config#15]
It would be nice to have support for the command line, possibly working in a mechanism similar to `#config/cli "--some-option"`, working somewhat like the existing `#config/env` parsing.

It would be nice if we can support short and long-form command line flags too, so `--some-option` as well as `-o`.

If this isn't already the case, it would be nice if we can hook in a default parser function so that we can restrict the input to integers for example, or maybe even more restricted (such as a port, which would be an integer in [1 .. 65,535])

**Comment by pjstadig** [comment]
There are two issues here.  The first is the idea of having a #config/cli option. The second is the idea of having a parser/validator for those options. I think it would be perfectly reasonable to implement command-line parsing for your app, and define whatever default values you would like to have using outpace.config, but outpace.config should not get into the command-line parsing business.

I think the first issue is probably out-of-scope for this project for a few reasons:
1. There is a standard way to access environment variables. There is not a standard way to access command-line arguments. Some languages provide an ARGV or something, but Clojure does not.
2. There is not a standard command-line parsing library. Accessing the raw arguments is one thing, but specifying how they should be parsed is another. It's not clear to me how that parsing mechanism would be linked to the config.

As regards to the second issue, admittedly they are not parsers, but you can specify validators for config values.
